steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/f3data-simple-api', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/f3data-simple-api']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'f3data-simple-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/f3data-simple-api'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Remove this if you want to require authentication

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/f3data-simple-api'

options:
  logging: CLOUD_LOGGING_ONLY
